services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      UVICORN_RELOAD: "true"
    volumes:
      - ./src:/home/app_user/app/src # this will allow hot reload when file changes
